CREATE TABLE [dbo].[Abc]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY NONCLUSTERED,
	[GamePointsAbc] INT NOT NULL,
	[GameTypeAbc] NVARCHAR(30) NOT NULL,
	[DifficultyUnlocked] NVARCHAR(30) NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT [FK_Abc_User] FOREIGN KEY ([UserId]) REFERENCES [User]([Id])
)