CREATE TABLE [dbo].[Games]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY NONCLUSTERED,
	[GamePointsGames] INT NOT NULL,
	[GameTypeGames] NVARCHAR(30) NOT NULL,
	[DifficultyUnlocked] NVARCHAR(30) NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT [FK_Games_User] FOREIGN KEY ([UserId]) REFERENCES [User]([Id])
)