CREATE TABLE [dbo].[Math]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY NONCLUSTERED,
	[GamePointsMath] INT NOT NULL,
	[GameTypeMath] NVARCHAR(30) NOT NULL,
	[DifficultyUnlocked] NVARCHAR(30) NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT [FK_Math_User] FOREIGN KEY ([UserId]) REFERENCES [User]([Id])
)